In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, 7, 6, 8])

In [4]:
s

0    1
1    3
2    5
3    7
4    6
5    8
dtype: int64

In [6]:
s = pd.Series([1, 3, 5, 7, 6, 8], index=['a', 'b', 'c', 'd', 'e', 'f'])
s

a    1
b    3
c    5
d    7
e    6
f    8
dtype: int64

In [3]:
df=pd.DataFrame({"name":["anuj","kafi","anmol"],"age":[23,24,25]})
df

    name  age
0   anuj   23
1   kafi   24
2  anmol   25

In [15]:
df=pd.read_csv("graduation_rate (2).csv")
df

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
0,22,1625,high school,40999,3.0,3.1,7
1,29,2090,associate's degree,75817,4.0,3.4,5
2,30,2188,bachelor's degree,82888,4.0,3.9,3
3,33,2151,associate's degree,93518,4.0,3.7,5
4,29,2050,associate's degree,79153,4.0,3.4,6
...,...,...,...,...,...,...,...
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [20]:
df.tail()

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [25]:
print(df.memory_usage(deep=True).sum())

70564

In [30]:
df[["parental income", "parental level of education"]]

     parental income parental level of education
0              40999                 high school
1              75817          associate's degree
2              82888           bachelor's degree
3              93518          associate's degree
4              79153          associate's degree
..               ...                         ...
995            30658                some college
996            59443                some college
997            94415          associate's degree
998            31713            some high school
999            93832           bachelor's degree

[1000 rows x 2 columns]

In [31]:
df.dropna()

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
0,22,1625,high school,40999,3.0,3.1,7
1,29,2090,associate's degree,75817,4.0,3.4,5
2,30,2188,bachelor's degree,82888,4.0,3.9,3
3,33,2151,associate's degree,93518,4.0,3.7,5
4,29,2050,associate's degree,79153,4.0,3.4,6
...,...,...,...,...,...,...,...
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [32]:
df2=pd.read_csv("graduation_rate (2).csv")
df.fillna(0, inplace=True)

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
0,22,1625,high school,40999,3.0,3.1,7
1,29,2090,associate's degree,75817,4.0,3.4,5
2,30,2188,bachelor's degree,82888,4.0,3.9,3
3,33,2151,associate's degree,93518,4.0,3.7,5
4,29,2050,associate's degree,79153,4.0,3.4,6
...,...,...,...,...,...,...,...
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [36]:
df.rename(columns={"parental income":"p.i"})

,ACT composite score,SAT total score,parental level of education,p.i,high school gpa,college gpa,years to graduate
0,22,1625,high school,40999,3.0,3.1,7
1,29,2090,associate's degree,75817,4.0,3.4,5
2,30,2188,bachelor's degree,82888,4.0,3.9,3
3,33,2151,associate's degree,93518,4.0,3.7,5
4,29,2050,associate's degree,79153,4.0,3.4,6
...,...,...,...,...,...,...,...
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [37]:
df

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
0,22,1625,high school,40999,3.0,3.1,7
1,29,2090,associate's degree,75817,4.0,3.4,5
2,30,2188,bachelor's degree,82888,4.0,3.9,3
3,33,2151,associate's degree,93518,4.0,3.7,5
4,29,2050,associate's degree,79153,4.0,3.4,6
...,...,...,...,...,...,...,...
995,32,2234,some college,30658,4.0,3.0,10
996,27,1930,some college,59443,3.6,3.2,4
997,32,2117,associate's degree,94415,4.0,3.8,4
998,32,2034,some high school,31713,3.9,3.2,8
999,34,2268,bachelor's degree,93832,4.0,3.8,6

In [38]:
df.describe

<bound method NDFrame.describe of      ACT composite score  SAT total score parental level of education  \
0                     22             1625                 high school
1                     29             2090          associate's degree
2                     30             2188           bachelor's degree
3                     33             2151          associate's degree
4                     29             2050          associate's degree
..                   ...              ...                         ...
995                   32             2234                some college
996                   27             1930                some college
997                   32             2117          associate's degree
998                   32             2034            some high school
999                   34             2268           bachelor's degree

     parental income  high school gpa  college gpa  years to graduate
0              40999              3.0          3.1                  7
1              75817              4.0          3.4                  5
2              82888              4.0          3.9                  3
3              93518              4.0          3.7                  5
4              79153              4.0          3.4                  6
..               ...              ...          ...                ...
995            30658              4.0          3.0                 10
996            59443              3.6          3.2                  4
997            94415              4.0          3.8                  4
998            31713              3.9          3.2                  8
999            93832              4.0          3.8                  6

[1000 rows x 7 columns]>

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ACT composite score          1000 non-null   int64
 1   SAT total score              1000 non-null   int64
 2   parental level of education  1000 non-null   str
 3   parental income              1000 non-null   int64
 4   high school gpa              1000 non-null   float64
 5   college gpa                  1000 non-null   float64
 6   years to graduate            1000 non-null   int64
dtypes: float64(2), int64(4), str(1)
memory usage: 68.9 KB

In [41]:
df['parental income']=df['parental income'].astype('float64')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ACT composite score          1000 non-null   int64
 1   SAT total score              1000 non-null   int64
 2   parental level of education  1000 non-null   str
 3   parental income              1000 non-null   float64
 4   high school gpa              1000 non-null   float64
 5   college gpa                  1000 non-null   float64
 6   years to graduate            1000 non-null   int64
dtypes: float64(3), int64(3), str(1)
memory usage: 68.9 KB

In [42]:
len(df)

1000

In [44]:
df["zeros"]=[0 for i in range(len(df))]
df

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate,zeros
0,22,1625,high school,40999.0,3.0,3.1,7,0
1,29,2090,associate's degree,75817.0,4.0,3.4,5,0
2,30,2188,bachelor's degree,82888.0,4.0,3.9,3,0
3,33,2151,associate's degree,93518.0,4.0,3.7,5,0
4,29,2050,associate's degree,79153.0,4.0,3.4,6,0
...,...,...,...,...,...,...,...,...
995,32,2234,some college,30658.0,4.0,3.0,10,0
996,27,1930,some college,59443.0,3.6,3.2,4,0
997,32,2117,associate's degree,94415.0,4.0,3.8,4,0
998,32,2034,some high school,31713.0,3.9,3.2,8,0
999,34,2268,bachelor's degree,93832.0,4.0,3.8,6,0

In [47]:
def fx(a):
    return a+a
df["zeros+1"]=df["years to graduate"].apply(fx)
df

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate,zeros,zeros+1
0,22,1625,high school,40999.0,3.0,3.1,7,0,14
1,29,2090,associate's degree,75817.0,4.0,3.4,5,0,10
2,30,2188,bachelor's degree,82888.0,4.0,3.9,3,0,6
3,33,2151,associate's degree,93518.0,4.0,3.7,5,0,10
4,29,2050,associate's degree,79153.0,4.0,3.4,6,0,12
...,...,...,...,...,...,...,...,...,...
995,32,2234,some college,30658.0,4.0,3.0,10,0,20
996,27,1930,some college,59443.0,3.6,3.2,4,0,8
997,32,2117,associate's degree,94415.0,4.0,3.8,4,0,8
998,32,2034,some high school,31713.0,3.9,3.2,8,0,16
999,34,2268,bachelor's degree,93832.0,4.0,3.8,6,0,12

In [48]:
df.to_csv("graduation_rate (2).csv", index=False)

In [49]:
df1=pd.DataFrame({"name":["anuj","kafi","anmol"],"age":[23,24,25]})
df1

    name  age
0   anuj   23
1   kafi   24
2  anmol   25

In [50]:
df2=pd.DataFrame({"name":["anuj","kafi","anmol"],"marks":[23,24,25]})
df2

    name  marks
0   anuj     23
1   kafi     24
2  anmol     25

In [52]:
df3=pd.merge(df1,df2,on="name")
df3

    name  age  marks
0   anuj   23     23
1   kafi   24     24
2  anmol   25     25